name: 'core-infrastructure-apply'
description: 'apply core.infrastructure'
inputs:
  infrastructure-directory:
    description: infrastructure directory
    required: true
  app-name:
    description: APP_NAME
    required: true
  region:
    description: AWS_REGION
    required: true
  tf-bucket:
    description: TF_BACKEND_BUCKET_NAME
    required: true
  frontend-bucket:
    description: TF_VAR_FRONTEND_S3_BUCKET_NAME
    required: true
  environment:
    description: prod, test, COMMIT_ID
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    AWS_REGION: ${{ inputs.region }}
    TF_BACKEND_BUCKET_NAME: ${{ inputs.tf-bucket }}
    TF_BACKEND_BUCKET_PATH: ${{ inputs.environment }}/core.tfstate
    TF_VAR_GLOBAL_PREFIX: ${{ inputs.environment }}
    TF_VAR_FRONTEND_S3_BUCKET_NAME: ${{ inputs.frontend-bucket }}
    TF_VAR_RESOURCE_SHARING_BUCKET_NAME: ${{ inputs.resource-sharing-bucket }}
  args:
    - ${{ inputs.infrastructure-directory }}
