name: Identity.backend - Unit test
on:
  workflow_call:
jobs:
  identity-backend-unitTest:
    name: Identity.backend - Unit test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./identity/backend
    steps:
      - name: Backend Unit Test
        run: make test-unit
        shell: bash

      - name: Backend Usecase Test
        run: make test-usecase
        shell: bash
